#%RAML 1.0 NamedExample
value:

- 

    firstName: Jessica
    lastName: Jones
    address: temp address
    postal: 346725
    country: India
    miles: 100
    type: business
- 
    firstName: Tom
    lastName: Johns
    address: temp address
    postal: 346725
    country: India
    miles: 100
    type: business
- 
    firstName: Rachel
    lastName: Green
    address: abc colony
    postal: 56246
    country: India
    miles: 150
    type: personal