#%RAML 1.0 NamedExample
value:

- 
    id: 1
    firstName: Jessica
    lastName: Jones
    address: temp address
    postal: 346725
    country: India
    miles: 100
    creationDate: 2019-09-22T21:00:00Z
    type: business
- 
    id: 2
    firstName: Tom
    lastName: Johns
    address: temp address
    postal: 346725
    country: India
    miles: 100
    creationDate: 2018-12-12T21:00:00Z
    type: business
- 
    id: 3
    firstName: Rachel
    lastName: Green
    address: abc colony
    postal: 56246
    country: India
    miles: 150
    creationDate: 2019-10-30T21:00:00Z
    type: personal